[project]
name = 'stacks-web3-workshop'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.basic-token-swap]
path = 'contracts/basic-token-swap.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
