[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "assume weird spin renew pumpkin flat october scene stand hollow actual engine pumpkin approve venture miss tent chicken peace battle empower above venue slot"
